spring:
  profiles:
    active: local
restClient:
  movieInfoUrl: http://localhost:8080/v1/movieinfos
  reviewsUrl: http://localhost:8081/v1/reviews
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile:
        - local
  data:
    mongodb:
      uri: uri
      database: c1
